const programITM = {
  stage_1: {
    oct_4: [
      {
        id: 0,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Cisco',
        avatar: '',
        logo:'/futuristic-minds/img/slider/ciscopartner.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 1,
        id_s2: 2,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Oliver Castellanos | Sergio Romero',
        avatar: '/futuristic-minds/speakers/oliver-castellanos.webp',
        avatar2: '/futuristic-minds/speakers/sergio-romero.webp',
        rol: 'Solution Architect | Business Developer Manager for Power Quality & Energy Automation',
        institution: 'Schneider Electric',
        conference: 'Soluciones de calidad de la energía y digitalización para edificaciones inteligentes',
        resume: "¿Te imaginas tener el poder de mejorar la calidad y eficiencia de la energía en tus operaciones? Descubre cómo nuestras soluciones de vanguardia, presentados por nuestros expertos Oliver Castellanos, de Solutions Architect, y Sergio Romero, BDM de Power Quality & Energy Automation, pueden ser la convergencia perfecta entre la digitalización y la calidad de la energía para optimizar decisiones, reducir costos y mejorar la eficiencia de tus edificaciones. ¡Construyamos edificaciones inteligentes!"
      },
      {
        id: '',
        id_s2: '',
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Nokia',
        avatar: '',
        logo:'/futuristic-minds/img/slider/nokia.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 18,
        id_s2: '',
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Mariana Del Rocío García Dorantes',
        avatar: '/futuristic-minds/speakers/mariana-garcía.webp',
        logo: '',
        rol: 'Consultora en Transformación Digital y Sustentabilidad',
        institution: 'Siemens México, Centroamérica y el Caribe',
        conference: 'Industria 4.0 y el gemelo digital: Producto, Proceso y Desempeño',
        resume: 'Explora el emocionante mundo de la Industria 4.0 y su aplicación práctica a través del concepto de Gemelo Digital. Analizaremos los impactos transformadores de la tecnología en la fabricación y cómo los Gemelos Digitales están revolucionando la forma en que se diseñan, producen y optimizan productos y procesos industriales.'
      },
      {
        id: '',
        id_s2: '',
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'ROUE',
        avatar: '',
        logo: '/futuristic-minds/img/slider/roue.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 6,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Alfonso Feria Kaiser',
        avatar: '/futuristic-minds/speakers/alfonso-feria.webp',
        rol: 'Ingeniero de Sistemas',
        institution: 'Jet Propulsion Laboratory',
        conference: 'La Exploración Robótica del Universo',
        resume: "Compartirá una sinopsis sobre su educación, carrera, logros profesionales, y experiencias de trabajo, así como el camino que siguió para obtener un trabajo en el Laboratorio de Propulsión a Chorro (Jet Propulsion Laboratory, JPL) de la NASA. También explicará las funciones y características de la Red del Espacio Profundo (DSN) de JPL y detallará sobre algunas de las misiones robóticas de JPL, pasadas, presentes y futuras. El objetivo de esta plática es servir como inspiración para que estudiantes se animen a terminar sus estudios y den un paso más allá, fuera de su zona de confort."
      },
      {
        id: 3,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Maximiliano Hernández | Ramón Contreras',
        avatar: '',
        logo: '/futuristic-minds/img/slider/mitsubishi.webp',
        rol: 'Ingenieros de producto',
        institution: 'Mitsubishi',
        conference: 'Ellos también fueron jóvenes. La brecha generacional en la industria',
        resume: "INFORMACIÓN POR CONFIRMAR"
      },
      // {
      //   id: 4,
      //   hour: '17:00 hrs',
      //   duration: '45 min',
      //   name: 'Diego Sinhue Rodríguez Vallejo',
      //   avatar: '',
      //   rol: 'Gobernador del estado de Guanajuato',
      //   institution: 'Gobierno del Estado de Guanajuato',
      //   conference: 'Charla de estudiantes con el Gobernador de Guanajuato',
      //   resume: "INFORMACIÓN POR CONFIRMAR"
      // },
    ],
    oct_5: [
      {
        id: 0,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Ikesi',
        avatar: '',
        logo:'/futuristic-minds/img/slider/ikusi.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 3,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Mariana Cruz',
        avatar: '/futuristic-minds/speakers/mariana-cruz.webp',
        avatar2: '',
        rol: 'Sales Distributors Engineer',
        institution: 'Schneider Electric',
        conference: 'Estudiantes líderes: Las Industrias del Futuro están en tus manos',
        resume: '¡Un futuro impulsado por los estudiantes! Descubre cómo los estudiantes son los responsables de liderar las Industrias del futuro y generar el cambio en México por medio de la innovación, la digitalización y la automatización en los sectores industriales. Aprovecha tus habilidades y conocimientos para hacer una diferencia y forjar un futuro próspero.'
      },
      {
        id: 5,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Juan Carlos Valerio',
        avatar: '',
        logo:'/futuristic-minds/img/slider/mitsubishi.webp',
        id_s2: 0,
        avatar2: '',
        rol: 'Ventas de soluciones y servicios',
        institution: 'Mitsubishi',
        conference: 'Crecimiento profesional',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Siemens',
        avatar: '',
        logo:'/futuristic-minds/img/slider/siemens.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 4,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Leonardo Pérez',
        avatar: '/futuristic-minds/speakers/leonardo-perez.webp',
        logo:'',
        avatar2: '',
        rol: 'Industry Manager',
        institution: 'Endress + Hauser México',
        conference: 'Empower the School',
        resume: 'Programa para formar a los estudiantes de nivel universitario de carreras de ingenierías relacionadas a la industria de proceso enfocados en el control y la automatización'
      },
       {
        id: 0,
        id_s2: 0,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Secretaría de Educación de Guanajuato',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      // {
      //   id: 0,
      //   id_s2: 0,
      //   hour: '14:00 hrs',
      //   duration: '45 min',
      //   name: 'Secretaría de Educación de Guanajuato',
      //   avatar: '',
      //   logo:'/futuristic-minds/img/slider/edu_gto.webp',
      //   rol: '',
      //   institution: '',
      //   conference: 'INFORMACIÓN POR CONFIRMAR',
      //   resume: ''
      // },
      {
        id: 0,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Secretaría de Educación de Guanajuato',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: '',
        id_s2: '',
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Nokia',
        avatar: '',
        logo:'/futuristic-minds/img/slider/nokia.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
    ],
    oct_6: [
      {
        id: 0,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Cisco',
        avatar: '',
        logo:'/futuristic-minds/img/slider/ciscopartner.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 5,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Sac Nité Arzate',
        avatar: '/futuristic-minds/speakers/sac-nite.webp',
        id_s2: 5,
        avatar2: '',
        rol: 'Business Developer',
        institution: 'Schneider Electric',
        conference: 'Implicaciones del Edge computing en la Industria (HBN)',
        resume: 'El Edge computing está diseñada para acercar las aplicaciones y los datos a los dispositivos y a sus usuarios. Mientras que la computación en la nube impulsó la creación de megacentros de datos, el edge computing trae el poder de la TI distribuida, repartida en un número exponencial de microcentros de datos'
      },
      {
        id: 6,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Eduardo López | Alejandro Hora ',
        avatar: '',
        logo:'/futuristic-minds/img/slider/mitsubishi.webp',
        id_s2: 5,
        avatar2: '',
        rol: 'Socios Comerciales',
        institution: 'Mitsubishi',
        conference: 'México necesita emprendedores',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Siemens',
        avatar: '',
        logo:'/futuristic-minds/img/slider/siemens.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 0,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Secretaría de Educación de Guanajuato',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
    ]
  },
  stage_2: {
    oct_4: [
      {
        id: 7,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Amalia Anguiano',
        avatar: '/futuristic-minds/speakers/amalia-anguiano.webp',
        logo:'',
        rol: 'Encargada de cultura del Agua',
        institution: 'SAPAL',
        conference: 'Cultura del agua y Día Cero',
        resume: 'Analizaremos lo importante del agua en nuestra vida diaria, la situación que vivimos en nuestro municipio, así como trabajos y estrategias que el SAPAL realiza para poder abastecer a la ciudad en constante crecimiento. Se brindarán consejos para que los participantes puedan implementar acciones para su correcto uso y aprovechamiento.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'TBC SEG',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 8,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Manuel Sánchez Tello',
        avatar: '/futuristic-minds/speakers/manuel-sanchez.webp',
        logo:'',
        avatar2: '',
        rol: 'Consejero Delegado',
        institution: 'INSTITUTO OVIEDO',
        conference: 'Aprendizajes y retos sobre la electromovilidad en México',
        resume: 'El objetivo es conocer, mediante la experiencia, las ventajas de los vehículos eléctricos y su tecnología asociada.'
      },
      {
        id: 16,
        id_s2: 17,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Felipe Hernández Palafox | Miguel Salvador Gómez Díaz',
        avatar: '/futuristic-minds/speakers/felipe-hernandez.webp',
        avatar2: '/futuristic-minds/speakers/miguel-gomez.webp',
        logo:'',
        rol: 'Secretario Académico | Profesor de asignatura',
        institution: 'Universidad La Salle Bajío',
        conference: 'Inteligencia Artificial Generativa',
        resume: 'El auge de la Inteligencia Artificial (IA) ha revolucionado el panorama tecnológico actual, ofreciendo una amplia gama de aplicaciones que antes se consideraban inimaginables. Dentro de esta amplia gama, una rama particularmente intrigante es la de "Inteligencia Artificial Generativa". Este seminario se sumergirá en el fascinante mundo de las IAs que no sólo piensan, procesan y toman decisiones, sino que también crean, diseñan y generan contenido de manera autónoma.'
      },
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '14:00 hrs',
      //   duration: '45 min',
      //   name: 'Dr. Felipe Hernández Palafox | M.C. Miguel Salvador Gómez Díaz',
      //   avatar: '',
      //   avatar2: '',
      //   rol: 'Secretario Académico | Profesor de asignatura',
      //   institution: 'TBC La Salle Bajío',
      //   conference: 'Inteligencia Artificial Generativa',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // },
      {
        id: 11,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Laura Eugenia Alejandri Rábago',
        avatar: '/futuristic-minds/speakers/laura-alejandri.webp',
        avatar2: '',
        rol: 'Docente',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Subirse a la ola de la Responsabilidad Social ',
        resume: 'La Responsabilidad Social es un compromiso de todos. En esta charla, explicaremos conceptos clave, áreas de impacto y agentes implicados, junto con buenas prácticas realizadas desde el entorno escolar. El propósito es inspirar a los participantes a emprender acciones con el poder de transformar su entorno.'
      },
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '17:00 hrs',
      //   duration: '45 min',
      //   name: 'Elizabeth Mena Avilés',
      //   avatar: '',
      //   avatar2: '',
      //   rol: 'Directora de Programa Ingeniería Industrial y de Sistemas',
      //   institution: 'TBC Tecnológico de Monterrey',
      //   conference: 'Propuestas de valor desde la Ingeniería para el Diseño FinTech desde el enfoque del emprendimiento',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // },
      {
        id: 0,
        id_s2: 0,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'TBC SEG',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
    ],
    oct_5: [
      {
        id: 7,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Amalia Anguiano',
        avatar: '/futuristic-minds/speakers/amalia-anguiano.webp',
        logo:'',
        rol: 'Encargada de cultura del Agua',
        institution: 'SAPAL',
        conference: 'Cultura del agua y Día Cero',
        resume: 'Analizaremos lo importante del agua en nuestra vida diaria, la situación que vivimos en nuestro municipio, así como trabajos y estrategias que el SAPAL realiza para poder abastecer a la ciudad en constante crecimiento. Se brindarán consejos para que los participantes puedan implementar acciones para su correcto uso y aprovechamiento.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'TBC SEG',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 9,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Ramón Ayala Álvarez',
        avatar: '/futuristic-minds/speakers/ramon-ayala.webp',
        avatar2: '',
        rol: 'Profesor de Innovación y Emprendimiento',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Economía circular ¿Una alternativa para resolver las problemáticas ambientales?',
        resume: 'La Economía Circular es un concepto y un enfoque económico que se basa en la idea de minimizar el desperdicio de recursos, reducir la contaminación y maximizar la eficiencia al gestionar los productos, materiales y recursos a lo largo de su ciclo de vida. A diferencia del modelo económico tradicional, que se centra en la producción, uso y eliminación lineal de productos (llamado modelo económico lineal), la Economía Circular propone un enfoque más sostenible y regenerativo. Sin embargo, bastante se ha discutido acerca de la insuficiencia de esta alternativa como solución a los problemas que precisamente busca resolver. Discutiremos algunas de sus limitantes y posibilidades.'
      },
  
    ],
    oct_6: [
      {
        id: 10,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Ylutiere Reyes Campos',
        avatar: '/futuristic-minds/speakers/ylutiere-reyes.webp',
        avatar2: '',
        rol: 'Investigador',
        institution: 'YLUCA, Capacitación y Consultoría en empresa 4.0',
        conference: 'Inteligencia artificial, desde la diversión hasta la aplicación',
        resume: 'La inteligencia artificial ayuda a divertir a chicos y grandes: con los asistentes de voz inteligentes (Alexa), juegos y entretenimiento impulsados por la IA, sistemas de recomendación en plataformas streaming, chat bots de entretenimiento y editores de texto e imágenes. Seguramente tú ya los conoces, pero… ¿estos desarrollos sólo sirven para divertirte? Ven, acompáñame a descubrir, cómo algo tan divertido, también sirve en la industria y es capaz de crear diferentes productos. Te sorprenderás de la versatilidad de la inteligencia artificial.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'TBC SEG',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 13,
        id_s2: '',
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Karen Adriana García Ramírez',
        avatar: '/futuristic-minds/speakers/karen-adriana.webp',
        avatar2: '',
        logo: '',
        rol: 'Docente',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Gotas de conciencia: Navegando el cálculo de la huella hídrica',
        resume: 'El objetivo de este seminario es empoderar a los jóvenes con el conocimiento necesario para comprender y valorar el impacto de sus acciones en el uso del agua a nivel local y global. A través de la exploración en profundidad del cálculo de la huella hídrica para fomentar una mentalidad responsable y sostenible entre los jóvenes, alentándolos a tomar decisiones informadas y conscientes. Se busca inspirar la adopción de prácticas más eficientes en el uso del agua.'
      },
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '13:00 hrs',
      //   duration: '45 min',
      //   name: 'Héctor Javier Arismendi Valle',
      //   avatar: '',
      //   avatar2: '',
      //   logo: '/futuristic-minds/img/slider/edu_gto.webp',
      //   rol: 'Profesor de la Escuela de Ingenierías y Ciencias',
      //   institution: 'TBC Tecnológico de Monterrey',
      //   conference: 'La inteligencia artificial en la Robótica aplicada',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // }
    ]
  },
  stage_3: {
    oct_4: [
      {
        id: 12,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Erandi Teresa Ramírez García',
        avatar: '/futuristic-minds/speakers/erandi-teresa.webp',
        avatar2: '',
        rol: 'Coordinadora académica',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Convivencia y comunicación cotidiana: las habilidades sociales en el siglo XXI ',
        resume: 'Daremos a conocer la importancia de las habilidades sociales del siglo XXI. Mediante ejercicios de reflexión y análisis, buscamos hacer más conscientes a los jóvenes sobre que estas competencias son cada vez más importantes en el entorno laboral y social actual, para tener éxito en un mundo caracterizado por la interconexión global, la tecnología y el mundo digital. '
      },
      {
        id: 9,
        id_s2: 5,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Ramón Ayala Álvarez',
        avatar: '/futuristic-minds/speakers/ramon-ayala.webp',
        avatar2: '',
        rol: 'Profesor de Innovación y Emprendimiento',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Diseño especulativo para resolver problemas',
        resume: 'Aplicar herramientas creativas, de diseño especulativo y de ludificación para la búsqueda de solución a cualquier tipo de problema'
      },
      
    ],
    oct_5: [
      {
        id: 14,
        id_s2: '',
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'María Gutiérrez Rangel',
        avatar: '/futuristic-minds/speakers/maria-gutierrez.webp',
        avatar2: '',
        rol: 'Jefatura de innovación y emprendimiento',
        institution: 'INSTITUTO OVIEDO',
        conference: 'La importancia de un Pitch efectivo',
        resume: 'Aprender a estructurar un mensaje de manera clara y concisa, resaltando los puntos clave de un proyecto'
      },
      {
        id: 15,
        id_s2: '',
        hour: '17:00 hrs',
        duration: '45 min',
        name: 'Laura Eugenia Alejandri Rábago',
        avatar: '',
        avatar2: '',
        logo: '/futuristic-minds/img/slider/bachillerato-talentos.webp',
        rol: 'Docente',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Construyendo un Futuro Sostenible: Explorando los ODS en Nuestro Entorno',
        resume: 'Identificar los Objetivos del Desarrollo Sostenible en nuestro entorno y reconocer nuestras posibles acciones para aportar a su cumplimiento'
      },
    ],
    oct_6: [
      {
        id: 5,
        id_s2: 5,
        hour: '00:00 hrs',
        duration: '0 min',
        name: 'Por el momento, no se han confirmado speaker para este día',
        avatar: '',
        avatar2: '',
        rol: '',
        institution: '',
        conference: '',
        resume: ''
      },
    ]
  }
}
export { programITM }
