const programITM = {
  stage_1: {
    oct_4: [
      {
        id: 0,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Cisco',
        avatar: '',
        logo:'/futuristic-minds/img/slider/ciscopartner.webp',
        form: '',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 1,
        id_s2: 2,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Oliver Castellanos | Sergio Romero',
        avatar: '/futuristic-minds/speakers/oliver-castellanos.webp',
        avatar2: '/futuristic-minds/speakers/sergio-romero.webp',
        form: '',
        rol: 'Solution Architect | Business Developer Manager for Power Quality & Energy Automation',
        institution: 'Schneider Electric',
        conference: 'Soluciones de calidad de la energía y digitalización para edificaciones inteligentes',
        resume: "¿Te imaginas tener el poder de mejorar la calidad y eficiencia de la energía en tus operaciones? Descubre cómo nuestras soluciones de vanguardia, presentados por nuestros expertos Oliver Castellanos, de Solutions Architect, y Sergio Romero, BDM de Power Quality & Energy Automation, pueden ser la convergencia perfecta entre la digitalización y la calidad de la energía para optimizar decisiones, reducir costos y mejorar la eficiencia de tus edificaciones. ¡Construyamos edificaciones inteligentes!"
      },
      {
        id: 30,
        id_s2: '',
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Santiago Escalona',
        avatar: '/futuristic-minds/speakers/santiago-escalona.webp',
        logo:'',
        form: '',
        rol: 'Director de marketing estratégico',
        institution: 'Nokia',
        conference: 'Una empresa es tan inteligente como la gente que es parte de ella',
        resume: 'Las tecnologías de comunicación inalámbrica de misión crítica son un habilitador clave para acelerar el camino hacia la Industria 4.0, asegurando ventajas competitivas en términos de innovación, eficiencia y flexibilidad. Identificar las fortalezas y desafíos de integrar sistemas de comunicación en rápida evolución para desarrollar aplicaciones industriales competitivas y confiables requiere una fuerte cooperación y un entendimiento común entre todos los actores en la cadena de valor. En esta sesión, más allá de la tecnología, podremos ver lo valioso que son los recursos humanos y su formación como causal de esta 4ª revolución, la incorporación cada vez mayor de carreras STEAM en nuestro ámbito y formación diaria es fundamental en este proceso.'
      },
      {
        id: 18,
        id_s2: '',
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Mariana Del Rocío García Dorantes',
        avatar: '/futuristic-minds/speakers/mariana-garcía.webp',
        logo: '',
        form: '',
        rol: 'Consultora en Transformación Digital y Sustentabilidad',
        institution: 'Siemens México, Centroamérica y el Caribe',
        conference: 'Industria 4.0 y el gemelo digital: Producto, Proceso y Desempeño',
        resume: 'Explora el emocionante mundo de la Industria 4.0 y su aplicación práctica a través del concepto de Gemelo Digital. Analizaremos los impactos transformadores de la tecnología en la fabricación y cómo los Gemelos Digitales están revolucionando la forma en que se diseñan, producen y optimizan productos y procesos industriales.'
      },
      {
        id: 34,
        id_s2: 35,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Gautier Mignot | Wolfgang Dold',
        avatar: '/futuristic-minds/speakers/gautier-mignot.webp',
        avatar2: '/futuristic-minds/speakers/wolfgang-dold.webp',
        logo: '',
        form: '',
        rol: 'Embajador de la Unión Europea en México | Embajador de la República Federal de Alemania en México',
        institution: 'Delegación de la Unión Europea en México | Embajada de la República Federal de Alemania en México',
        conference: 'Foro con Embajadores',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 23,
        id_s2: '',
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'José Enrique Poceros Pérez',
        avatar: '/futuristic-minds/speakers/jose-enrique.webp',
        logo: '',
        form: '',
        rol: 'Chief Technology Officer',
        institution: 'ROUE',
        conference: 'Tecnologías emergentes que están preparando el futuro de la movilidad y la reducción de la huella de CO2',
        resume: 'Esta charla aborda la nueva generación de vehículos eléctricos y cómo los fabricantes están utilizando las tecnologías como Blockchain, Edge Computing y Ciberseguridad para reducir su huella de CO2 en componentes y proceso de manufactura.'
      },
      {
        id: 6,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Alfonso Feria Kaiser',
        avatar: '/futuristic-minds/speakers/alfonso-feria.webp',
        rol: 'Ingeniero de Sistemas',
        form: '',
        institution: 'Jet Propulsion Laboratory',
        conference: 'La Exploración Robótica del Universo',
        resume: "Compartirá una sinopsis sobre su educación, carrera, logros profesionales, y experiencias de trabajo, así como el camino que siguió para obtener un trabajo en el Laboratorio de Propulsión a Chorro (Jet Propulsion Laboratory, JPL) de la NASA. También explicará las funciones y características de la Red del Espacio Profundo (DSN) de JPL y detallará sobre algunas de las misiones robóticas de JPL, pasadas, presentes y futuras. El objetivo de esta plática es servir como inspiración para que estudiantes se animen a terminar sus estudios y den un paso más allá, fuera de su zona de confort."
      },
      {
        id: 5,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Juan Carlos Valerio',
        avatar: '',
        logo:'/futuristic-minds/img/slider/mitsubishi.webp',
        id_s2: 0,
        avatar2: '',
        form: '',
        rol: 'Ventas de soluciones y servicios',
        institution: 'Mitsubishi',
        conference: 'Crecimiento profesional',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 36,
        hour: '17:00 hrs',
        duration: '45 min',
        name: 'Diego Sinhue Rodríguez Vallejo',
        avatar: '/futuristic-minds/speakers/DiegoSinhue.webp',
        form: '',
        rol: 'Gobernador Constitucional del Estado de Guanajuato',
        institution: 'Gobierno del Estado de Guanajuato',
        conference: 'Charla de estudiantes con el Gobernador de Guanajuato',
        resume: "INFORMACIÓN POR CONFIRMAR"
      },
    ],
    oct_5: [
      {
        id: 31,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Orlando Hernández López',
        avatar: '/futuristic-minds/speakers/orlando-hernández.webp',
        logo:'',
        rol: 'Arquitecto de ciberseguridad',
        form: '',
        institution: 'IKUSI',
        conference: 'La importancia de la ciberseguridad en los ambientes industriales',
        resume: 'En esta charla, los asistentes podrán conocer los antecedentes de cómo el sector industrial se ha venido transformando con iniciativas digitales, sin embargo, es de suma importancia conocer que un factor de éxito para dichas iniciativas es considerar la ciberseguridad en todo momento, por la relevancia en el aumento de la exposición de riesgos en las convergencias de intercomunicación de sistemas de IT con los esquemas de Tecnologías de Operación (OT).'
      },
      {
        id: 37,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'David Herrera',
        avatar: '/futuristic-minds/speakers/david-herrera.webp',
        logo:'',
        rol: 'Sales Engineer OEM',
        form: '',
        institution: 'Schneider Electric',
        conference: 'Estudiantes líderes: las Industrias del Futuro están en tus manos',
        resume: '¡Un futuro impulsado por los estudiantes! Descubre cómo los estudiantes son los responsables de liderar las Industrias del futuro y generar el cambio en México por medio de la innovación, la digitalización y la automatización en los sectores industriales. Aprovecha tus habilidades y conocimientos para hacer una diferencia y forjar un futuro próspero.'
      },
      // {
      //   id: 3,
      //   id_s2: 0,
      //   hour: '10:00 hrs',
      //   duration: '45 min',
      //   name: 'Mariana Cruz',
      //   avatar: '/futuristic-minds/speakers/mariana-cruz.webp',
      //   avatar2: '',
      //   form: '',
      //   rol: 'Sales Distributors Engineer',
      //   institution: 'Schneider Electric',
      //   conference: 'Estudiantes líderes: Las Industrias del Futuro están en tus manos',
      //   resume: '¡Un futuro impulsado por los estudiantes! Descubre cómo los estudiantes son los responsables de liderar las Industrias del futuro y generar el cambio en México por medio de la innovación, la digitalización y la automatización en los sectores industriales. Aprovecha tus habilidades y conocimientos para hacer una diferencia y forjar un futuro próspero.'
      // },
      {
        id: 32,
        id_s2: 0,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Maximiliano Hernández | Christian Landeros',
        avatar: '/futuristic-minds/speakers/maximiliano-hernandez.webp',
        logo: '',
        form: '',
        rol: 'Ingenieros de producto',
        institution: 'Mitsubishi',
        conference: 'Ellos también fueron jóvenes. La brecha generacional en la industria',
        resume: "INFORMACIÓN POR CONFIRMAR"
      },
      {
        id: 18,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Mariana Del Rocío García Dorantes',
        avatar: '/futuristic-minds/speakers/mariana-garcía.webp',
        logo:'',
        form: '',
        rol: 'Consultora en Transformación Digital y Sustentabilidad',
        institution: 'Siemens México, Centroamérica y el Caribe',
        conference: 'Estrategias y herramientas para la Descarbonización Industrial',
        resume: 'A lo largo de esta conferencia, exploraremos las estrategias innovadoras, así como las herramientas prácticas diseñadas para ayudar a las empresas industriales a descarbonizar sus procesos y operaciones. Definiremos una hoja de ruta para que las organizaciones avancen hacia una producción industrial más sostenible y respetuosa con el medio ambiente.'
      },
      {
        id: 4,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Leonardo Pérez',
        avatar: '/futuristic-minds/speakers/leonardo-perez.webp',
        logo:'',
        avatar2: '',
        form: '',
        rol: 'Industry Manager',
        institution: 'Endress + Hauser México',
        conference: 'Empower the School',
        resume: 'Programa para formar a los estudiantes de nivel universitario de carreras de ingenierías relacionadas a la industria de proceso enfocados en el control y la automatización'
      },
       {
        id: 38,
        id_s2: 0,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Ernesto Enei Chi',
        avatar: '/futuristic-minds/speakers/ernesto-chai.webp',
        logo:'',
        rol: '',
        form: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'Avance de los vehículos híbridos y eléctricos a través de la historia',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      // {
      //   id: 0,
      //   id_s2: 0,
      //   hour: '14:00 hrs',
      //   duration: '45 min',
      //   name: 'Secretaría de Educación de Guanajuato',
      //   avatar: '',
      //   logo:'/futuristic-minds/img/slider/edu_gto.webp',
      //   rol: '',
      //   institution: '',
      //   conference: 'INFORMACIÓN POR CONFIRMAR',
      //   resume: ''
      // },
      {
        id: 0,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Salvador Cruz',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        form: '',
        rol: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'Electromovilidad. Líneas de acción para enfrentar este reto',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 39,
        id_s2: 0,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Antonio Reus',
        avatar: '/futuristic-minds/speakers/antonio-reus.webp',
        logo:'',
        form: '',
        rol: 'Director General',
        institution: 'IDEA GTO',
        conference: 'Tecnología para Emprender',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 30,
        id_s2: '',
        hour: '17:00 hrs',
        duration: '45 min',
        name: 'Santiago Escalona',
        avatar: '/futuristic-minds/speakers/santiago-escalona.webp',
        logo:'',
        form: '',
        rol: 'Director de marketing estratégico',
        institution: 'Nokia',
        conference: 'Una empresa es tan inteligente como la gente que es parte de ella',
        resume: 'Las tecnologías de comunicación inalámbrica de misión crítica son un habilitador clave para acelerar el camino hacia la Industria 4.0, asegurando ventajas competitivas en términos de innovación, eficiencia y flexibilidad. Identificar las fortalezas y desafíos de integrar sistemas de comunicación en rápida evolución para desarrollar aplicaciones industriales competitivas y confiables requiere una fuerte cooperación y un entendimiento común entre todos los actores en la cadena de valor. En esta sesión, más allá de la tecnología, podremos ver lo valioso que son los recursos humanos y su formación como causal de esta 4ª revolución, la incorporación cada vez mayor de carreras STEAM en nuestro ámbito y formación diaria es fundamental en este proceso.'
      }
      // {
      //   id: '',
      //   id_s2: '',
      //   hour: '16:00 hrs',
      //   duration: '45 min',
      //   name: 'Nokia',
      //   avatar: '',
      //   logo:'/futuristic-minds/img/slider/nokia.webp',
      //   rol: '',
      //   institution: '',
      //   conference: 'INFORMACIÓN POR CONFIRMAR',
      //   resume: ''
      // },
    ],
    oct_6: [
      {
        id: 0,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Cisco',
        avatar: '',
        logo:'/futuristic-minds/img/slider/ciscopartner.webp',
        rol: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 5,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Sac Nité Arzate',
        avatar: '/futuristic-minds/speakers/sac-nite.webp',
        id_s2: 5,
        avatar2: '',
        rol: 'Business Developer',
        institution: 'Schneider Electric',
        conference: 'Implicaciones del Edge computing en la Industria (HBN)',
        resume: 'El Edge computing está diseñada para acercar las aplicaciones y los datos a los dispositivos y a sus usuarios. Mientras que la computación en la nube impulsó la creación de megacentros de datos, el edge computing trae el poder de la TI distribuida, repartida en un número exponencial de microcentros de datos'
      },
      {
        id: 6,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Eduardo López | Alejandro Hora ',
        avatar: '',
        logo:'/futuristic-minds/img/slider/mitsubishi.webp',
        id_s2: 0,
        avatar2: '',
        rol: 'Socios Comerciales',
        institution: 'Mitsubishi',
        conference: 'México necesita emprendedores',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 19,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Josué Nieto',
        avatar: '/futuristic-minds/speakers/josue-nieto.webp',
        logo:'',
        rol: 'Especialista de Recursos Humanos ',
        institution: 'Siemens México, Centroamérica y el Caribe',
        conference: 'Future Makers',
        resume: 'Una carrera con propósito es algo que muchos anhelan, pero pocos logran encontrar. Trabajar en algo que te permita cumplir tu pasión, aprovechar tu experiencia y tener un impacto real en la sociedad es complejo. En Siemens lo hacemos posible, al transformar las grandes ideas en realidad. Te invitamos a que conozcas cómo es que la tecnología con propósito transforma el día a día de millones de personas, incluso, la de nuestros colaboradores.'
      },
      {
        id: 40,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Juan Manuel Luna',
        avatar: '/futuristic-minds/speakers/juan-luna.webp',
        logo:'',
        rol: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'De la idea a la electromovilidad',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
    ]
  },
  stage_2: {
    oct_4: [
      {
        id: 7,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Amalia Anguiano',
        avatar: '/futuristic-minds/speakers/amalia-anguiano.webp',
        logo:'',
        form: '',
        rol: 'Encargada de cultura del Agua',
        institution: 'SAPAL',
        conference: 'Cultura del agua y Día Cero',
        resume: 'Analizaremos lo importante del agua en nuestra vida diaria, la situación que vivimos en nuestro municipio, así como trabajos y estrategias que el SAPAL realiza para poder abastecer a la ciudad en constante crecimiento. Se brindarán consejos para que los participantes puedan implementar acciones para su correcto uso y aprovechamiento.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Ellis Spiezia',
        avatar: '/futuristic-minds/speakers/ellis-spiezia.webp',
        logo:'',
        form: '',
        rol: 'Piloto de carreras',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'Go Karts Eléctricos',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 20,
        id_s2: 21,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'René García Contreras | Benjamín Aranda Herrera ',
        avatar: '/futuristic-minds/speakers/rene-garcia.webp',
        avatar2: '/futuristic-minds/speakers/benjamin-aranda.webp',
        logo:'',
        form: '',
        rol: 'Coordinador de la Licenciatura de Odontología y Titular de la UNIPEV UNAM ENES León',
        institution: 'ENES UNAM',
        conference: 'IA en Ciencias de la Salud',
        resume: 'Brindar el contexto de la IA en sus aplicaciones en el ámbito de salud'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Beatriz Álvarez Granados',
        avatar: '',
        avatar2: '',
        logo:'/futuristic-minds/img/slider/juventudes.webp',
        form: '',
        rol: 'Jefa de innovación para el desarrollo juvenil y formación especializada',
        institution: 'Juventudes GTO',
        conference: '',
        resume: ''
      },
      {
        id: 8,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Manuel Sánchez Tello',
        avatar: '/futuristic-minds/speakers/manuel-sanchez.webp',
        logo:'',
        form: '',
        avatar2: '',
        rol: 'Consejero Delegado',
        institution: 'INSTITUTO OVIEDO',
        conference: 'Aprendizajes y retos sobre la electromovilidad en México',
        resume: 'El objetivo es conocer, mediante la experiencia, las ventajas de los vehículos eléctricos y su tecnología asociada.'
      },
      {
        id: 16,
        id_s2: 17,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Felipe Hernández Palafox | Miguel Salvador Gómez Díaz',
        avatar: '/futuristic-minds/speakers/felipe-hernandez.webp',
        avatar2: '/futuristic-minds/speakers/miguel-gomez.webp',
        logo:'',
        form: '',
        rol: 'Secretario Académico | Jefe académico de pregrado de Ingeniería de Software y Sistemas Computacionales',
        institution: 'Universidad La Salle Bajío',
        conference: 'Inteligencia Artificial Generativa',
        resume: 'El auge de la Inteligencia Artificial (IA) ha revolucionado el panorama tecnológico actual, ofreciendo una amplia gama de aplicaciones que antes se consideraban inimaginables. Dentro de esta amplia gama, una rama particularmente intrigante es la de "Inteligencia Artificial Generativa". Este seminario se sumergirá en el fascinante mundo de las IAs que no sólo piensan, procesan y toman decisiones, sino que también crean, diseñan y generan contenido de manera autónoma.'
      },
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '14:00 hrs',
      //   duration: '45 min',
      //   name: 'Dr. Felipe Hernández Palafox | M.C. Miguel Salvador Gómez Díaz',
      //   avatar: '',
      //   avatar2: '',
      //   rol: 'Secretario Académico | Profesor de asignatura',
      //   institution: 'TBC La Salle Bajío',
      //   conference: 'Inteligencia Artificial Generativa',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // },
      {
        id: 11,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Laura Eugenia Alejandri Rábago',
        avatar: '/futuristic-minds/speakers/laura-alejandri.webp',
        avatar2: '',
        form: '',
        rol: 'Docente',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Subirse a la ola de la Responsabilidad Social ',
        resume: 'La Responsabilidad Social es un compromiso de todos. En esta charla, explicaremos conceptos clave, áreas de impacto y agentes implicados, junto con buenas prácticas realizadas desde el entorno escolar. El propósito es inspirar a los participantes a emprender acciones con el poder de transformar su entorno.'
      },
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '17:00 hrs',
      //   duration: '45 min',
      //   name: 'Elizabeth Mena Avilés',
      //   avatar: '',
      //   avatar2: '',
      //   rol: 'Directora de Programa Ingeniería Industrial y de Sistemas',
      //   institution: 'TBC Tecnológico de Monterrey',
      //   conference: 'Propuestas de valor desde la Ingeniería para el Diseño FinTech desde el enfoque del emprendimiento',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // },
      {
        id: 41,
        id_s2: 0,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Dinorah Arellano Lara ',
        avatar: '/futuristic-minds/speakers/dinorah-arellano.webp',
        logo:'',
        form: '',
        rol: 'Docente',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'Electromovilidad una solución sostenible',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
    ],
    oct_5: [
      {
        id: 7,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Amalia Anguiano',
        avatar: '/futuristic-minds/speakers/amalia-anguiano.webp',
        logo:'',
        form: '',
        rol: 'Encargada de cultura del Agua',
        institution: 'SAPAL',
        conference: 'Cultura del agua y Día Cero',
        resume: 'Analizaremos lo importante del agua en nuestra vida diaria, la situación que vivimos en nuestro municipio, así como trabajos y estrategias que el SAPAL realiza para poder abastecer a la ciudad en constante crecimiento. Se brindarán consejos para que los participantes puedan implementar acciones para su correcto uso y aprovechamiento.'
      },
      {
        id: 43,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Gerardo Vázquez Guzmán',
        avatar: '/futuristic-minds/speakers/gerardo-vazquez.webp',
        logo:'',
        form: '',
        rol: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'La ingeniería de la electrónica de potencia en la electromovilidad ',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 33,
        id_s2: 0,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Rigoberto García Contreras',
        avatar: '/futuristic-minds/speakers/rigoberto-garcia.webp',
        logo:'',
        form: '',
        rol: 'Profesor',
        institution: 'ENES UNAM',
        conference: 'La revolución de la educación: la IA transformando el aprendizaje',
        resume: 'Brindar las herramientas de IA en el aprendizaje'
      },
      {
        id: 24,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Rocío Bretchnaider',
        avatar: '/futuristic-minds/speakers/img-woman.webp',
        logo:'',
        form: '',
        rol: 'COO',
        institution: 'Metaphorce Tech',
        conference: 'Comunicación 4.0: ¿Qué es y cómo afecta a la industria 4.0?',
        resume: 'La Comunicación 4.0 se refiere a un enfoque de comunicación que se ha vuelto esencial en la era de la industria 4.0, caracterizada por la digitalización, la automatización, la inteligencia artificial y la interconexión de dispositivos y sistemas. La importancia de la comunicación 4.0 radica en varios aspectos clave:Conexión y colaboración, Toma de decisiones informadas, Automatización y eficiencia, Personalización, Mejora de la experiencia del cliente, Innovación y competitividad, Adaptabilidad y resiliencia, Seguridad y privacidad, Sostenibilidad'
      },
      {
        id: 44,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Beatriz Álvarez Granados',
        avatar: '/futuristic-minds/speakers/beatriz-alvarez.webp',
        avatar2: '',
        form: '',
        logo:'',
        rol: 'Jefa de innovación para el desarrollo juvenil y formación especializada',
        institution: 'Juventudes GTO',
        conference: 'Mentes Ágiles = Juventudes Destacadas',
        resume: '"El talento que la era digital demanda incluye el dominio de habilidades sociales y emocionales que, combinadas con rasgos personales y otras competencias de carácter profesional, ofrecen ventajas en el desempeño laboral y suman a tu perfil profesional. En escenarios de trabajo cada vez más colaborativos, son un valor profesional esencial.” En la Industria 4.0, la tecnología está cambiando la forma en que trabajamos, lo que significa que las habilidades técnicas ya no son suficientes. Las empresas buscan profesionales que puedan adaptarse rápidamente a los cambios, trabajar de manera colaborativa y comunicarse efectivamente a través de diferentes canales. Las habilidades blandas son fundamentales en la Industria 4.0 porque permiten a los profesionales trabajar de manera efectiva en equipos multidisciplinarios, resolver problemas complejos y liderar en un entorno de trabajo en constante cambio, esto es un poco de lo que se abordará en el seminario.'
      },
      {
        id: 33,
        id_s2: 0,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Rigoberto García Contreras',
        avatar: '/futuristic-minds/speakers/rigoberto-garcia.webp',
        logo:'',
        form: '',
        rol: 'Profesor',
        institution: 'ENES UNAM',
        conference: 'Explorando tendencias a través del análisis de sentimientos: Un ejemplo sobre la evolución del consumo durante la pandemia',
        resume: 'Presentaremos un estudio de análisis de sentimientos sobre la evolución del consumo durante la pandemia, como un ejemplo concreto de cómo esta técnica puede proporcionar información valiosa para las empresas y organizaciones que buscan adaptarse a un entorno cambiante.'
      },
      {
        id: 9,
        id_s2: 0,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Ramón Ayala Álvarez',
        avatar: '/futuristic-minds/speakers/ramon-ayala.webp',
        avatar2: '',
        logo:'',
        form: '',
        rol: 'Profesor de Innovación y Emprendimiento',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Economía circular ¿Una alternativa para resolver las problemáticas ambientales?',
        resume: 'La Economía Circular es un concepto y un enfoque económico que se basa en la idea de minimizar el desperdicio de recursos, reducir la contaminación y maximizar la eficiencia al gestionar los productos, materiales y recursos a lo largo de su ciclo de vida. A diferencia del modelo económico tradicional, que se centra en la producción, uso y eliminación lineal de productos (llamado modelo económico lineal), la Economía Circular propone un enfoque más sostenible y regenerativo. Sin embargo, bastante se ha discutido acerca de la insuficiencia de esta alternativa como solución a los problemas que precisamente busca resolver. Discutiremos algunas de sus limitantes y posibilidades.'
      },
      {
        id: 26,
        id_s2: 0,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Elizabeth Mena Avilés ',
        avatar: '/futuristic-minds/speakers/elizabeth_mena.webp',
        avatar2: '',
        logo:'',
        form: '',
        rol: 'Directora de Programa Ingeniería Industrial y de Sistemas',
        institution: 'Tecnológico de Monterrey campus León',
        conference: 'Propuestas de valor desde la Ingeniería para el Diseño FinTech desde el enfoque del emprendimiento',
        resume: 'Compartir algunos resultados y propuestas generadas desde  el enfoque de Innovación y Emprendimiento donde la ingeniería utiliza la tecnología al servicio del mundo financiero para permitir a clientes potenciales acceder y obtener servicios bancarios.'
      },
      {
        id: 24,
        id_s2: 0,
        hour: '17:00 hrs',
        duration: '45 min',
        name: 'Rocío Bretchnaider',
        avatar: '/futuristic-minds/speakers/img-woman.webp',
        avatar2: '',
        logo:'',
        form: '',
        rol: 'COO',
        institution: 'Metaphorce Tech',
        conference: 'La influencia de la AI en los softskills',
        resume: 'La Inteligencia Artificial (IA) está empezando a tener un impacto significativo en el desarrollo y la evaluación de las habilidades blandas o soft skills. Las soft skills son habilidades interpersonales y sociales que incluyen la comunicación efectiva, la empatía, la resolución de conflictos, la toma de decisiones, el trabajo en equipo y muchas otras.'
      },
  
    ],
    oct_6: [
      {
        id: 10,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Ylutiere Reyes Campos',
        avatar: '/futuristic-minds/speakers/ylutiere-reyes.webp',
        avatar2: '',
        rol: 'Investigador',
        institution: 'YLUCA, Capacitación y Consultoría en empresa 4.0',
        conference: 'Inteligencia artificial, desde la diversión hasta la aplicación',
        resume: 'La inteligencia artificial ayuda a divertir a chicos y grandes: con los asistentes de voz inteligentes (Alexa), juegos y entretenimiento impulsados por la IA, sistemas de recomendación en plataformas streaming, chat bots de entretenimiento y editores de texto e imágenes. Seguramente tú ya los conoces, pero… ¿estos desarrollos sólo sirven para divertirte? Ven, acompáñame a descubrir, cómo algo tan divertido, también sirve en la industria y es capaz de crear diferentes productos. Te sorprenderás de la versatilidad de la inteligencia artificial.'
      },
      {
        id: 45,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Juan De Anda Suárez',
        avatar: '/futuristic-minds/speakers/juan-suarez.webp',
        logo:'',
        rol: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'Paradigmas de la Inteligencia Artificial en la electromovilidad',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 13,
        id_s2: '',
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Karen Adriana García Ramírez',
        avatar: '/futuristic-minds/speakers/karen-adriana.webp',
        avatar2: '',
        logo: '',
        rol: 'Docente',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Gotas de conciencia: Navegando el cálculo de la huella hídrica',
        resume: 'El objetivo de este seminario es empoderar a los jóvenes con el conocimiento necesario para comprender y valorar el impacto de sus acciones en el uso del agua a nivel local y global. A través de la exploración en profundidad del cálculo de la huella hídrica para fomentar una mentalidad responsable y sostenible entre los jóvenes, alentándolos a tomar decisiones informadas y conscientes. Se busca inspirar la adopción de prácticas más eficientes en el uso del agua.'
      },
      {
        id: 44,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Beatriz Álvarez Granados',
        avatar: '/futuristic-minds/speakers/beatriz-alvarez.webp',
        avatar2: '',
        form: '',
        logo:'',
        rol: 'Jefa de innovación para el desarrollo juvenil y formación especializada',
        institution: 'Juventudes GTO',
        conference: 'Mentes Ágiles = Juventudes Destacadas',
        resume: '"El talento que la era digital demanda incluye el dominio de habilidades sociales y emocionales que, combinadas con rasgos personales y otras competencias de carácter profesional, ofrecen ventajas en el desempeño laboral y suman a tu perfil profesional. En escenarios de trabajo cada vez más colaborativos, son un valor profesional esencial.” En la Industria 4.0, la tecnología está cambiando la forma en que trabajamos, lo que significa que las habilidades técnicas ya no son suficientes. Las empresas buscan profesionales que puedan adaptarse rápidamente a los cambios, trabajar de manera colaborativa y comunicarse efectivamente a través de diferentes canales. Las habilidades blandas son fundamentales en la Industria 4.0 porque permiten a los profesionales trabajar de manera efectiva en equipos multidisciplinarios, resolver problemas complejos y liderar en un entorno de trabajo en constante cambio, esto es un poco de lo que se abordará en el seminario.'
      },
      {
        id: 46,
        id_s2: 5,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Miguel Ángel Gil Rios',
        avatar: '/futuristic-minds/speakers/miguel-rios.webp',
        avatar2: '',
        logo: '',
        rol: 'Profesor',
        institution: 'Universidad Tecnológica de León',
        conference: 'Inteligencia Artificial Aplicada en Medicina',
        resume: 'Uno de los campos con mayor impacto debido a la evolución de la Inteligencia Artificial es la Medicina. Pues, el propósito de esta última es prolongar la vida del ser humano. En este contexto y, con base en los datos publicados por el INEGI en el año 2022, las enfermedades asociadas al corazón son la primera causa de muerte en México. Por tal motivo, el desarrollo de conocimiento y herramientas computacionales enfocadas en este tipo de enfermedades, como son los casos de estenosis coronaria, es relevante.'
      }
      // {
      //   id: 5,
      //   id_s2: 5,
      //   hour: '13:00 hrs',
      //   duration: '45 min',
      //   name: 'Héctor Javier Arismendi Valle',
      //   avatar: '',
      //   avatar2: '',
      //   logo: '/futuristic-minds/img/slider/edu_gto.webp',
      //   rol: 'Profesor de la Escuela de Ingenierías y Ciencias',
      //   institution: 'TBC Tecnológico de Monterrey',
      //   conference: 'La inteligencia artificial en la Robótica aplicada',
      //   resume: 'INFORMACIÓN POR CONFIRMAR'
      // }
    ]
  },
  stage_3: { 
    oct_4: [
      {
        id: 27,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'José Guadalupe Almanza Mireles',
        avatar: '/futuristic-minds/speakers/jose-guadalupe.webp',
        avatar2: '',
        form: 'https://forms.gle/nXvqxHPNgDJwgeNDA',
        rol: 'Instructor',
        institution: 'IECA Instituto de Educación y Desarrollo Richard E. Dauch',
        conference: 'Taller de sistemas de visión artificial',
        resume: 'Conocer los conceptos básicos de los sistemas de visión artificial y realizar procesamiento de imagen de acuerdo a herramientas de programación IN SIGHT de COGNEX.'
      },
      {
        id: 12,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Erandi Teresa Ramírez García',
        avatar: '/futuristic-minds/speakers/erandi-teresa.webp',
        avatar2: '',
        form: '',
        rol: 'Coordinadora académica',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Convivencia y comunicación cotidiana: las habilidades sociales en el siglo XXI ',
        resume: 'Daremos a conocer la importancia de las habilidades sociales del siglo XXI. Mediante ejercicios de reflexión y análisis, buscamos hacer más conscientes a los jóvenes sobre que estas competencias son cada vez más importantes en el entorno laboral y social actual, para tener éxito en un mundo caracterizado por la interconexión global, la tecnología y el mundo digital. '
      },
      {
        id: 28,
        id_s2: 0,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Nicolás Rafael Mena Guzmán',
        avatar: '/futuristic-minds/speakers/nicolas-mena.webp',
        avatar2: '',
        form: 'https://forms.gle/Pb3N7kx77b9iAUYW7',
        rol: '',
        institution: 'IECA Instituto de Educación y Desarrollo Richard E. Dauch',
        conference: 'Taller de Impresión 3D con NX',
        resume: 'Conocer los principios de  la interfaz y herramientas del software NX para la generación de piezas mecánicas y su posible aplicación en Impresión 3D.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Secretaría de Educación de Guanajuato',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        form: '',
        institution: '',
        conference: 'Inauguración Summit de Electromovilidad E-GTO',
        resume: ''
      },
      {
        id: 47,
        id_s2: 0,
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Antonio Benjamín Pascual Tacea',
        avatar: '/futuristic-minds/speakers/antonio-pascual.webp',
        logo:'',
        rol: 'CEO Masare Moto',
        form: '',
        institution: 'Secretaría de Educación de Guanajuato',
        conference: 'El ADN del Futuro especialista en Electromovilidad',
        resume: 'INFORMACIÓN POR CONFIRMAR'
      },
      {
        id: 25,
        id_s2: 0,
        hour: '14:00 hrs',
        duration: '45 min',
        name: 'Héctor Javier Arismendi Valle',
        avatar: '/futuristic-minds/speakers/hector-arismendi.webp',
        logo:'',
        rol: 'Profesor de la Escuela de Ingenierías y Ciencias',
        form: '',
        institution: 'Tecnológico de Monterrey campus León',
        conference: 'La inteligencia artificial en la Robótica aplicada',
        resume: 'Proporcionar a los participantes un profundo entendimiento de cómo la Inteligencia Artificial se aplica en el campo de la robótica, explorando las últimas tendencias, avances y desafíos, y dar una perspectiva general para diseñar, desarrollar y operar sistemas robóticos inteligentes.'
      },
      {
        id: 9,
        id_s2: 5,
        hour: '15:00 hrs',
        duration: '45 min',
        name: 'Ramón Ayala Álvarez',
        avatar: '/futuristic-minds/speakers/ramon-ayala.webp',
        avatar2: '',
        form: '',
        rol: 'Profesor de Innovación y Emprendimiento',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Diseño especulativo para resolver problemas',
        resume: 'Aplicar herramientas creativas, de diseño especulativo y de ludificación para la búsqueda de solución a cualquier tipo de problema'
      },
      {
        id: 26,
        id_s2: 0,
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'Elizabeth Mena Avilés',
        avatar: '/futuristic-minds/speakers/elizabeth_mena.webp',
        avatar2: '',
        form: '',
        rol: 'Directora de Programa Ingeniería Industrial y de Sistemas',
        institution: 'Tecnológico de Monterrey campus León',
        conference: 'Herramientas que contribuyen a la Logística Inteligente',
        resume: 'Reconocer algunas herramientas que, desde la Ingeniería, se han sumado en las cadenas de suministro para hablar de logística 4.0 y su valor desde la definición y la mejora continua de los procesos'
      },
      
    ],
    oct_5: [
      {
        id: 0,
        id_s2: 22,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Francisco Gasca Vargas | Francisco Gustavo Mota Muñoz',
        avatar: '',
        avatar2: '/futuristic-minds/speakers/francisco-mota.webp',
        logo: '',
        rol:'',
        form: 'https://forms.gle/txfDoAaFZxmZVyp68',
        institution: 'Universidad Politécnica de Guanajuato',
        conference: 'Taller PLC Básico Factory IO',
        resume: 'Taller diseñado para estudiantes y profesores interesados en aprender los principios de automatización y control de procesos industriales mediante PLCs. Se hace uso de un simulador Factory IO, donde es posible modelar desde una pequeña banda transportadora hasta una compleja celda de manufactura. Además, se contará con bancos de pruebas, equipados con PLC y HMIs.'
      },
      {
        id: 22,
        id_s2: '',
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Francisco Gustavo Mota Muñoz',
        avatar: '/futuristic-minds/speakers/francisco-mota.webp',
        avatar2: '',
        logo: '',
        rol:'',
        form: 'https://forms.gle/RQntKdTucXnZVaZT8',
        institution: 'Universidad Politécnica de Guanajuato',
        conference: 'Taller Robótica Educativa Libre',
        resume: 'Daremos a conocer herramientas y materiales didácticos accesibles, para implementar la educación STEAM en el estado de Guanajuato. Durante el taller los asistentes aprenderán de manera interactiva conceptos de: Electrónica, Programación, Automatización y Robótica. Empleando novedosas herramientas tales como: simuladores web TinkerCAD, software PictoBlox didáctico, kits de robótica educativa libre basado en la tarjeta Arduino UNO, con el cual se controlará un carrito robot. Como material de apoyo y consulta se utilizará el Cuadernillo: Introducción al Internet de las Cosas a través de la Robótica Educativa Libre, desarrollado por el Instituto de Gestión Educativa para la Secretaría de Educación de Guanajuato'
      },
      {
        id: 0,
        id_s2: 22,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Juan Lomas Guevara | Francisco Gustavo Mota Muñoz',
        avatar: '',
        avatar2: '/futuristic-minds/speakers/francisco-mota.webp',
        logo: '',
        rol:'',
        form: 'https://forms.gle/yvxcJpstyGP3fNr27',
        institution: 'Universidad Politécnica de Guanajuato',
        conference: 'Taller Manufactura aditiva y diseño 3D',
        resume: 'Taller diseñado para estudiantes interesadas en aprender a materializar sus ideas, proyectos y prototipos, mediante el diseño por computadora y la manufactura en 3D, una de las tecnologías que están impulsando el desarrollo de la Industria 4.0'
      },
      {
        id: 0,
        id_s2: 22,
        hour: '12:00 hrs',
        duration: '45 min',
        name: 'Pedro Jorge de los Santos Lara | Francisco Gustavo Mota Muñoz',
        avatar: '',
        avatar2: '/futuristic-minds/speakers/francisco-mota.webp',
        logo: '',
        rol:'',
        form: 'https://forms.gle/ZvfrfQDmrQ8j1tzB7',
        institution: 'Universidad Politécnica de Guanajuato',
        conference: 'Taller Introducción a Python',
        resume: 'Taller diseñado para toda persona que desee emprender sus primeros pasos en el mundo de la codificación, y aprender los conceptos básicos de este lenguaje de alto nivel multiplataforma, y el cual hoy en día tiene un sin fin de aplicaciones. El taller tiene como finalidad capacitar a profesores y alumnos, para que desarrollen scripts básicos de manejo de variables, funciones, tipos de datos, matemáticas y representación de funciones.'
      },
      {
        id: 22,
        id_s2: '',
        hour: '13:00 hrs',
        duration: '45 min',
        name: 'Francisco Gustavo Mota Muñoz',
        avatar: '/futuristic-minds/speakers/francisco-mota.webp',
        avatar2: '',
        logo: '',
        rol: '',
        form: 'https://forms.gle/UErsqHB4nyHyW7Nx7',
        institution: 'Universidad Politécnica de Guanajuato',
        conference: 'Taller Crea un chatbot mediante IBM Watson',
        resume: 'Taller diseñado para toda persona interesada en dar sus primeros pasos en el uso de la Inteligencia Artificial empleando PaaS en la nube. Se hará uso de IBM Cloud en conjunto con IBM Watson, una de las API de IA más potentes actualmente.'
      },
      {
        id: 0,
        id_s2: 0,
        hour: '14:00 hrs',
        duration: '90 min',
        name: 'Secretaría de Educación de Guanajuato',
        avatar: '',
        logo:'/futuristic-minds/img/slider/edu_gto.webp',
        rol: '',
        form: '',
        institution: '',
        conference: 'INFORMACIÓN POR CONFIRMAR',
        resume: ''
      },
      {
        id: 14,
        id_s2: '',
        hour: '16:00 hrs',
        duration: '45 min',
        name: 'María Gutiérrez Rangel',
        avatar: '/futuristic-minds/speakers/maria-gutierrez.webp',
        avatar2: '',
        rol: 'Jefatura de innovación y emprendimiento',
        form: '',
        institution: 'INSTITUTO OVIEDO',
        conference: 'La importancia de un Pitch efectivo',
        resume: 'Aprender a estructurar un mensaje de manera clara y concisa, resaltando los puntos clave de un proyecto'
      },
      {
        id: 11,
        id_s2: '',
        hour: '17:00 hrs',
        duration: '45 min',
        name: 'Laura Eugenia Alejandri Rábago',
        avatar: '/futuristic-minds/speakers/laura-alejandri.webp',
        avatar2: '',
        logo: '',
        rol: 'Docente',
        form: '',
        institution: 'Escuela de Talentos Guanajuato Azteca',
        conference: 'Construyendo un Futuro Sostenible: Explorando los ODS en Nuestro Entorno',
        resume: 'Identificar los Objetivos del Desarrollo Sostenible en nuestro entorno y reconocer nuestras posibles acciones para aportar a su cumplimiento'
      },
    ],
    oct_6: [
      {
        id: 29,
        id_s2: 0,
        hour: '09:00 hrs',
        duration: '45 min',
        name: 'Hugo Iván Buenrostro Vázquez',
        avatar: '/futuristic-minds/speakers/hugo-buenrostro.webp',
        avatar2: '',
        rol: '',
        institution: 'Itesoluciones - Contpaqi',
        conference: 'Lego Serious Play',
        resume: 'El curso taller Lego Serious Play es una metodología utilizada en procesos de innovación y resolución de problemas que utiliza piezas de Lego para representar ideas, conceptos y situaciones complejas. El taller es una experiencia de aprendizaje en la que se enseña a los participantes a utilizar esta metodología para potenciar la creatividad, la comunicación, el trabajo en equipo y la toma de decisiones.'
      },
      {
        id: 29,
        id_s2: 0,
        hour: '10:00 hrs',
        duration: '45 min',
        name: 'Hugo Iván Buenrostro Vázquez',
        avatar: '/futuristic-minds/speakers/hugo-buenrostro.webp',
        avatar2: '',
        rol: '',
        institution: 'Itesoluciones - Contpaqi',
        conference: 'Lego Serious Play',
        resume: 'El curso taller Lego Serious Play es una metodología utilizada en procesos de innovación y resolución de problemas que utiliza piezas de Lego para representar ideas, conceptos y situaciones complejas. El taller es una experiencia de aprendizaje en la que se enseña a los participantes a utilizar esta metodología para potenciar la creatividad, la comunicación, el trabajo en equipo y la toma de decisiones.'
      },
      {
        id: 29,
        id_s2: 0,
        hour: '11:00 hrs',
        duration: '45 min',
        name: 'Hugo Iván Buenrostro Vázquez',
        avatar: '/futuristic-minds/speakers/hugo-buenrostro.webp',
        avatar2: '',
        rol: '',
        institution: 'Itesoluciones - Contpaqi',
        conference: 'Lego Serious Play',
        resume: 'El curso taller Lego Serious Play es una metodología utilizada en procesos de innovación y resolución de problemas que utiliza piezas de Lego para representar ideas, conceptos y situaciones complejas. El taller es una experiencia de aprendizaje en la que se enseña a los participantes a utilizar esta metodología para potenciar la creatividad, la comunicación, el trabajo en equipo y la toma de decisiones.'
      },
    ]
  }
}
export { programITM }
